#
#

name: "Release"
'on': pull_request

jobs:
  Release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ github.ref }}
          prerelease: true
          title: "Development Build"
          files: |
            LiteLibria/archive/*.zip