name: Release

on:
  push:
    tags:
      - v*

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: '! [[ $GITHUB_REF =~ -release$ ]]'
      - run: '! [[ ${GITHUB_REF:10} =~ ^v[0-9]+$ ]]'

  release:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build

      - name: Push tag for released action
        run: |
          rm -rf node_modules
          yarn install --production
          git config --global user.email "marp-team@marp.app"
          git config --global user.name "Marp team"
          git add -f lib node_modules
          git commit -m "${GITHUB_REF:10} release"
          git tag "${GITHUB_REF:10}-release"
          git push origin refs/tags/${GITHUB_REF:10}-release
          if [[ ${GITHUB_REF:10} =~ ^(v[0-9]+)\.[^-]+$ ]]; then
            git push origin :refs/tags/${BASH_REMATCH[1]}
            git tag -f ${BASH_REMATCH[1]}
            git push origin refs/tags/${BASH_REMATCH[1]}
          fi