#
#

name: "Release"

'on': pull_request

jobs:
  Release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - run: npm ci && npm run build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.zip