#
#

name: "Release"
'on': pull_request

jobs:
  Release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build"
        run: npm ci && npm run build

      - name: Upload archives to release
      - uses: "./archive/"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref }}
          prerelease: true
          title: "Development Build"
          files: |
            README.md
            archive/*.zip