#
#

name: "Release"
'on': pull_request

jobs:
  Release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build"
        run: |
          echo "done!"

      - uses: "rozenrod/LiteLibria@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref }}
          prerelease: true
          title: "Development Build"
          files: |
            README.md
            archive/archive-2.0.5.zip